baseURL = "https://www.marketiseme.com"
languageCode = "bg-BG"
title = "Marketise Me | Дигитален маркетинг и реклама"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
# googleAnalytics = "UA-134294022-1"

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "bg"

# Site Params
[params]
    logo = "images/logo.png"
    # Gestion des langues : FR / EN / NL / DE
    [[Params.listeLangues]]
    code = "bg"
    [[Params.listeLangues]]
    code = "en"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    ############ 1 - Site en FRANCAIS
    [Languages.bg]
    weight = 1
    languageCode = "bg"
    title = "Marketise Me – Full Service Digital Agency"
    dateFormat = "2 January 2006"

    home = "Начало"
    logo = "images/logo.png"
    menufixed = true
    cookieText = "Този сайт използва \"бисквитки\"!"

    footerServiceTitle = "Услуги"
    footerQuicklinkTitle = "Последвайте ни"    
    footerAboutTitle = "IN DIGITAL WE TRUST"
    footerSubscribeTitle = "Subscribe"
    facebookLink = "https://www.facebook.com/marketizme"
    linkedinLink = "https://www.linkedin.com/company/marketise-me/"
    mailLink = "mailto:office@marketizme.com"
    # footerSubscribeTitle = "FRANCAIS Subscribe"

    # Hero Area Section
    [Languages.bg.params.hero]
        heading = "Ние сме Marketise Me"
        description = "Marketise Me предлага 360&#176; дигитални маркетинг услуги, <br />които създават идентичност,изграждат марки, стимулират<br />взаимодейстивието и получаването на резултати"
        btnText = "ИЗПРАТИ ЗАПИТВАНЕ"
    # About 2 Section
    [Languages.bg.params.aboutSm]
        enable  = true
        title   = "Дигитално развитие за вашия бранд!"
        description = "<strong>Предлагаме ви: дигитален маркетинг в социалните мрежи, изработка на уебсайт, онлайн магазини, онлайн платформи и приложения. <br><br>Маркетинг консултации, онлайн реклама, реклама във Фейсбук, реклама в Инстаграм, поддръжка на социални мрежи, поддръжка на Фейсбук страница, поддръжка Инстаграм профил, SEO, реклама в Google, Youtube маркетинг, LinkedIn реклама, креативен дизайн и уебдизайн.</strong>"

    # Blog Section On Homepage
    [Languages.bg.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "FRANCAIS Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.bg.params.contact]
        enable  = true
        topTitle= ""
        title   = "Контакти"
        subtitle= "За въпроси и консултации можете да се обърнете към нас по всяко едно време!"
        contactFormTitle = "Контактна форма"
        addressTitle = "Адрес"
        ctaTitle = "Позвънете"
        socialChannelsTitle = "В социалните мрежи"        
        address = "ул. Димитър Хаджикоцев 12 <br> София, България"
        phone   = "+359 888 252 679"
        # fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/marketizme/"
        # twitter = "https://twitter.com/"
        # linkedin= "https://www.linkedin.com/"
        mail= "office@marketizme.com"
        # instagram= "https://www.instagram.com/marketizme/"
        mapLatitude = "42.677487"
        mapLongitude= "23.320236"
        mapMarker   = "images/marker.png"

        formNames = "Имена"
        formEmail = "Email"
        formTelephone = "Телефон"
        formSubject = "Тема"
        formMessage = "Съобщение"
        formSubmit = "ИЗПРАТИ"

    # Call to Action Section on About Page
    [Languages.bg.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Създаваме съдържание, което носи стойност и привлича нови клиенти!"
        subtitle= "Свържете се с нас сега."
        btnText = "Позвънете"

    ############# 2 - Site en ENGLISH
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Marketise Me - Full Service Digital Agency."
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logo.png"
    menufixed = true
    cookieText = "We use \"Cookies\""

    # footerDescription = "Marketise Me is a team of young and motivated people striving perfectionism."
    footerServiceTitle = "Service"
    footerQuicklinkTitle = "Follow us"
    footerAboutTitle = "IN DIGITAL WE TRUST"
    footerSubscribeTitle = "Subscribe"
    facebookLink = "https://www.facebook.com/marketizme"
    # instagramLink = "https://www.instagram.com/marketizme/"
    linkedinLink = "https://www.linkedin.com/company/marketise-me/"
    mailLink = "mailto:office@marketizme.com"

    # Hero Area Section
    [Languages.en.params.hero]
        heading = "We are Marketise Me"
        description = "Marketise Me offers 360&#176; digital marketing services, <br />that create identity, build brands, stimulate<br />interactions and drive results"
        btnText = "GET A QUOTE"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "Digital development for your brand!"
        description = "<strong>We offer online marketing in the social channels, website development, e-commerce, apps. <br><br>Marketing consultations, online advertisements, advertisements in Facebook and Instragram, brand engagement in the social channels (Facebook and Instagram), SEO, Google advertisement, creative design and webdesign.</strong>"

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        contactFormTitle = "Email us"
        title   = "Contact Us."
        subtitle= "\n"
        addressTitle = "Address"
        ctaTitle = "Call Us"
        socialChannelsTitle = "Social Channels"
        address = "Dimitar Hadzhikotsev 12, Sofia, Bulgaria 1421"
        phone   = "+359 888 252 679 "
        # fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/marketizme/"
        # twitter = "https://twitter.com/"
        # linkedin= "https://www.linkedin.com/"
        mail= "office@marketizme.com"
        # instagram= "https://www.instagram.com/marketizme/"
        mapLatitude = "42.677487"
        mapLongitude= "23.320236"
        mapMarker   = "images/marker.png"

        formNames = "Names"
        formEmail = "Email"
        formTelephone = "Telephone number"
        formSubject = "Subject"
        formMessage = "Message"
        formSubmit = "SUBMIT"
  
    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Let's Create Something Together"
        subtitle= ""
        btnText = "Call Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 2
    [[menu.nav]]
        name    = "portfolio"
        url     = "uploads/portfolio-bg.pdf"
        weight  = 3
    [[menu.nav]]
        name    = "working-process"
        url     = "service/working-process"
        weight  = 4
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "webdesign"
        url     = "service/webdesign/"
        weight  = 1
    [[menu.service]]
        name    = "social"
        url     = "service/social/"
        weight  = 2
    [[menu.service]]
        name    = "design"
        url     = "service/design"
        weight  = 3
    [[menu.service]]
        name    = "ads"
        url     = "service/ad-campaign"
        weight  = 4
    [[menu.service]]
        name    = "sem"
        url     = "service/sem"
        weight  = 5
    [[menu.service]]
        name    = "marketing-consult"
        url     = "service/marketing-consult"
        weight  = 6



    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
